export const GET_ALL_COMMENT_SAGA = 'GET_ALL_COMMENT_SAGA'
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'




export const DELETE_COMMENT_SAGA = 'DELETE_COMMENT_SAGA'


export const EDIT_COMMENT_SAGA = 'EDIT_COMMENT_SAGA'



export const EDIT_COMMENT_REDUCER = 'EDIT_COMMENT_REDUCER'





export const INSERT_COMMENT_SAGA = 'INSERT_COMMENT_SAGA'

