export const GET_ALL_STATUS_API_SAGA = 'GET_ALL_STATUS_API_SAGA'
export const GET_ALL_STATUS_API = 'GET_ALL_STATUS_API'



export const UPDATE_TASK_STATUS_SAGA_DONE_TEXT = 'UPDATE_TASK_STATUS_SAGA_DONE_TEXT'


