export const GELL_ALL_TASK_TYPE = 'GELL_ALL_TASK_TYPE'
export const GELL_ALL_TASK_TYPE_SAGA = 'GELL_ALL_TASK_TYPE_SAGA'




export const UPDATE_TASK_STATUS_SAGA_DONE_TEXT = "UPDATE_TASK_STATUS_SAGA_DONE_TEXT"